### ISSUE TITLE
Prepare initial release

### ISSUE THREAD

**Issue by paulrobertlloyd** [paulrobertlloyd/markdown-it-handle#1]
Following [Cédric Aellen’s initial idea](https://alienlebarge.ch/notes/20230326175845/), a plugin for [`markdown-it`](https://github.com/markdown-it/markdown-it) that converts handles into links to user profile pages.

For example, given this Markdown:

```md
@paulrobertlloyd@micro.blog, @paulrobertlloyd@twitter.com and @paulrobertlloyd@mastodon.social.
```

using this plugin will generate the following HTML markup (lines wrapped for clarity):

```html
<p>
  <a href="https://micro.blog/paulrobertlloyd" rel="external">@paulrobertlloyd</a>,
  <a href="https://twitter.com/paulrobertlloyd" rel="external">@paulrobertlloyd</a> and
  <a href="https://mastodon.social/@paulrobertlloyd" rel="external">@paulrobertlloyd</a>.
</p>
```

Currently there are 2 options; you can change the link behaviour for given hosts (i.e Flickr username URLs don’t use the `@` symbol, but are proceeded by `/photos/`), and the attributes used on the link (for example, `class`, `rel`, etc.) can be altered. Need to think how these are handled; do options override defaults, or get merged with them? That said, let’s not overthink this!

@alienlebarge - you’ve inspired me! Do you want to give this a try on your site (and would you like to contribute to this project?)

## To do

- [x] Consider plugin options, and how user options are combined with defaults
- [x] Test on a website
- [x] Add more tests
- [x] Complete test coverage
- [x] Documentation

**Comment by alienlebarge** [comment]
Thanks for the mention and the offer to collaborate.
I may try it out tonight.

**Comment by paulrobertlloyd** [comment]
Fixed a pretty gnarly bug (no text would be output in bare text strings!), have now got full test coverage, added a number of different tests, and written up some documentation.

Take a look and let me know if this all makes sense, and that I’ve covered everything!

**Comment by paulrobertlloyd** [comment]
Baring any other issues, looks like this package is ready to be published. Two questions:

1. Would you like to be add to the `contributors` field in `package.json`? If so, with what details?
2. What do you think to the name of this package? I note your function was called `socialHandle`, maybe it should be that? Here are some options I’ve considered:

   * markdown-it-social-mention
   * markdown-it-federated-mention
   * markdown-it-handle
   * markdown-it-social-handle
   * markdown-it-user-handle
   * markdown-it-username-handle

    Including handle is perhaps a better option. I don’t know if there’s a more specific name for the `@username@host` format. Mentions may happen as a result of using this, but not necessarily, so maybe that shouldn’t be included in the package’s name?

**Comment by paulrobertlloyd** [comment]
Nope… found another bug… need to add some more tests for strings that contain links, but not with a matching string.

**Comment by paulrobertlloyd** [comment]
Fixed!

**Comment by alienlebarge** [comment]
> 1. Would you like to be add to the `contributors` field in `package.json`? If so, with what details?

Nope thanks. You are the personne who does the job ;)

> 2. What do you think to the name of this package? I note your function was called `socialHandle`, maybe it should be that? Here are some options I’ve considered:
> 
> * `markdown-it-social-mention`
> * `markdown-it-federated-mention`
> * `markdown-it-handle`
> * `markdown-it-social-handle`
> * `markdown-it-user-handle`
> * `markdown-it-username-handle`
> * `markdown-it-account-handle`
> 
> Including ‘handle’ is perhaps a better option. I don’t know if there’s a more specific name for the `@username@host` format. Mentions may happen as a result of using this plugin, but not necessarily, so maybe that shouldn’t be included in the name?

I agree with you.
For me, the _mention_ is the whole post: the handle and the content.

I have done some researche and "handle" seems to be the most common word to describe `@username@host`.
- https://www.google.com/search?q=user+handle
- https://www.google.com/search?q=social+handle

As this plugin converts the _handle_ and not the _mention_, using the word "handle" in the name seems more appropriate than "mention".
I won't use the word social. The site is not always a social network. Vimeo (`user@vimeo.com`) is not really a social network.

For me `markdown-it-user-handle` and `markdown-it-username-handle` are the two best one.

**Comment by alienlebarge** [comment]
I get errors with the plugin. Apparently it's due to something in the markdown's front matter.
https://github.com/alienlebarge/alienlebargech-v3/pull/178

**Comment by alienlebarge** [comment]
> I’ve added an additional check for `children` before checking for `children[0].type`, which may fix this.

Nice !
Sadly, I have updated the plugin but still get the error. Will investigate when I get time

> Also note I’ve updated the package name to `markdown-it-handle`.

👌 perfect

**Comment by alienlebarge** [comment]
I Found the problem https://github.com/alienlebarge/alienlebargech-v3/pull/178#issuecomment-1492471854

Everything is ok for me now 😅

**Comment by paulrobertlloyd** [comment]
[Released](https://www.npmjs.com/package/markdown-it-handle)!
